[features]
seeds = false
skip-lint = false
[programs.localnet]
calculator = "H5sGxN4aqyuH3StHo1pBXQZNzBgX56jEK7XRakSWVm41"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/asmar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
