[features]
seeds = false
skip-lint = false
[programs.localnet]
calculator = "4a5yKFWgw7ZrKkj3VgJgu1MxU2UwH68cWdGYvi4rNdrE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/asmar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
